http:
  address: ":3000"
  readtimeout: 30
  writetimeout: 30
  idletimeout: 60
  domain: "localhost:3000"
  cookieexpiry: 30

log:
  level: "info"
  format: "text"
  filename: ""
  maxsize: 500
  maxage: 7
  maxbackups: 5
  localtime: false
  compress: true

mongo:
  host : "" 
  port: 27017
  username: ""
  password: "" 
  db : ""
  poolSize: 10
